spring:
  application:
    name: project

  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: TRACE

security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000

resilience4j.retry:
  instances:
    orderService:
      max-attempts: 3
      wait-duration:
        seconds: 5
server:
  port: 8081